name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cd somewhere
        run: |
          pwd
          mkdir stuff/
          cd stuff/
          echo "::group::My title"
          pwd
          echo "::endgroup::"
          pwd

      - name: What my workdir now
        run: |
          pwd
          false
